version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn -Dmaven.test.skip=true package
      - store_artifacts:
          path: Koi-Bootstrap/target/Koi.jar

workflows:
  version: 2

  build:
    jobs:
      - build